export const START = "_START";
export const SUCCESS = "_SUCCESS";
export const FAIL = "_FAIL";

export default {
  auth: {
    AUTH_GET_USER: "AUTH_GET_USER",
    AUTH_GET_USER_ORDERS: "AUTH_GET_USER_ORDERS",
    AUTH_SET_USER_ADDRESSES: "AUTH_SET_USER_ADDRESSES",
    AUTH_SIGN_UP: "AUTH_SIGN_UP",
    AUTH_LOG_IN: "AUTH_LOG_IN",
    AUTH_LOG_OUT: "AUTH_LOG_OUT"
  },
  notifications: {
    ENQUEUE_SNACKBAR: "ENQUEUE_SNACKBAR",
    CLOSE_SNACKBAR: "CLOSE_SNACKBAR",
    REMOVE_SNACKBAR: "REMOVE_SNACKBAR"
  },
  products: {
    GET_PRODUCTS: "GET_PRODUCTS",
    GET_PRODUCT_PAGE: "GET_PRODUCT_PAGE",
    GET_SUGGESTIONS: "GET_SUGGESTIONS",
    EMPTY_SUGGESTIONS: "EMPTY_SUGGESTIONS",
    SET_SUBHEADER_TITLE: "SET_SUBHEADER_TITLE"
  },
  cart: {
    CHANGE_DELIVERY: "CHANGE_DELIVERY",
    SUBMIT_SHIPPING: "SUBMIT_SHIPPING",
    SUBMIT_BILLING: "SUBMIT_BILLING",
    VALIDATE_CART: "VALIDATE_CART",
    SUBMIT_CHECKOUT: "SUBMIT_CHECKOUT",
    ADD_CART_ITEM: "ADD_CART_ITEM",
    DELETE_CART_ITEM: "DELETE_CART_ITEM",
    UPDATE_CART_ITEM: "UPDATE_CART_ITEM"
  }
};
