export const START = '_START'
export const SUCCESS = '_SUCCESS'
export const FAIL = '_FAIL'
// AUTH
export const FETCH_MEMBER_START = 'FETCH_MEMBER_START'
export const FETCH_MEMBER_SUCCESS = 'FETCH_MEMBER_SUCCESS'
export const FETCH_MEMBER_FAIL = 'FETCH_MEMBER_FAIL'

export const SET_SHIPPING = 'SET_SHIPPING'
export const SET_BILLING = 'SET_BILLING'

export const AUTH_SIGN_UP = 'AUTH_SIGN_UP'
export const AUTH_LOG_IN = 'LOG_IN'
export const AUTH_LOG_OUT = 'AUTH_LOG_OUT'
export const AUTH_ERROR = 'AUTH_ERROR'

// TRIGERS
export const OPEN_MENU = 'OPEN_MENU'
export const CLOSE_MENU = 'CLOSE_MENU'
export const TOGGLE_FILTER = 'TOGGLE_FILTER'

// PRODUCTS
export const SORT_BY_PRICE = 'SORT_BY_PRICE'
export const ADD_FILTER = 'ADD_FILTER'
export const REMOVE_FILTER = 'REMOVE_FILTER'
export const RESET_FILTER = 'RESET_FILTER'
export const FILTER_PRODUCTS_WITH_URL = 'FILTER_PRODUCTS_WITH_URL'
export const SEARCH = 'SEARCH'

export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'

// CART
export const NEXT_STEP = 'NEXT_STEP'
export const PREV_STEP = 'PREV_STEP'
export const CHANGE_DELIVERY = 'CHANGE_DELIVERY'
export const SUBMIT_SHIPPING = 'SUBMIT_SHIPPING'
export const SUBMIT_CHECKOUT = 'SUBMIT_CHECKOUT'
export const ADD_TO_CART = 'ADD_TO_CART'
export const DELETE_CART_PRODUCT = 'DELETE_CART_PRODUCT'
export const CHANGE_PRODUCT_QUANTITY = 'CHANGE_PRODUCT_QUANTITY'
export const CHANGE_PRODUCT_SIZE = 'CHANGE_PRODUCT_SIZE'
export const EMPTY_CART = 'EMPTY_CART'
export const RESET_CART = 'RESET_CART'
export const TOTAL_PRICE_RECALCULATION = 'TOTAL_PRICE_RECALCULATION'

// SEARCHBOX
export const SET_SUGGESTIONS = 'SET_SUGGESTIONS'
export const EMPTY_SUGGESTIONS = 'EMPTY_SUGGESTIONS'
